services:
  apache:
    image: bitnami/apache:2.4
    container_name: apache-server
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
      - ./vhost.conf:/opt/bitnami/apache/conf/vhosts/myapp-vhost.conf
    depends_on:
      - php

  php:
    image: bitnami/php-fpm:8.1
    container_name: php-server
    volumes:
      - ./src:/app
    environment:
      - PHP_EXTENSION_DIR=/opt/bitnami/php/lib/php/extensions
      - PHP_EXTENSIONS=mysqli,pdo_mysql

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: monksdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"

